// Code generated by "stringer -type=StandardCode"; DO NOT EDIT.

package fault

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid - -1]
}

const _StandardCode_name = "Invalid"

var _StandardCode_index = [...]uint8{0, 7}

func (i StandardCode) String() string {
	i -= -1
	if i < 0 || i >= StandardCode(len(_StandardCode_index)-1) {
		return "StandardCode(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _StandardCode_name[_StandardCode_index[i]:_StandardCode_index[i+1]]
}
