// Code generated by "stringer -type=StdFaultCode"; DO NOT EDIT.

package errs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OperationFail-0]
}

const _StdFaultCode_name = "OperationFail"

var _StdFaultCode_index = [...]uint8{0, 13}

func (i StdFaultCode) String() string {
	if i < 0 || i >= StdFaultCode(len(_StdFaultCode_index)-1) {
		return "StdFaultCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StdFaultCode_name[_StdFaultCode_index[i]:_StdFaultCode_index[i+1]]
}
